<div id="passwordReset" class="ui two column page grid" data-bind="if: show">
  <div class="column">
    <div class="ui labeled vertical fluid inverted">
      <div  class="ui form segment">
        <form data-bind="submit: PasswordReset">
          <div class="ui success message" data-bind="style: { display: resp() ? 'block' : 'none'} " style="display: none;" >
            <div class="header" data-bind="text: resp"></div>
          </div>
          <div class="ui error message" data-bind="style: { display: error() ? 'block' : 'none'} " style="display: none;" >
            <div class="header" data-bind="text: error"></div>
          </div>
          <p>Please choose new password</p>
          <div class="field">
            <label>Password</label>
            <div class="ui left labeled icon input">
              <input type="text" data-bind="value: password">
              <i class="lock icon"></i>
              <div class="ui corner label">
                <i class="icon lock"></i>
              </div>
            </div>
          </div>
          <div class="field">
            <label>Password Confirmation</label>
            <div class="ui left labeled icon input">
              <input type="text" data-bind="value: password_confirmation">
              <i class="lock icon"></i>
              <div class="ui corner label">
                <i class="icon lock"></i>
              </div>
            </div>
          </div>
		  <div class="ui blue submit button" data-bind="click: login">Change</div>
        </form>
      </div>
    </div>
  </div><!-- /end column -->
</div><!-- /end passwordReset -->
