<div id="passwordResetRequest" class="ui two column page grid" style="display: none;" data-bind="if: show">
  <div class="column">
    <div class="ui labeled vertical fluid inverted">
      <div  class="ui form segment">
        <form data-bind="submit: PasswordResetRequest">
          <div class="ui success message" data-bind="style: { display: resp() ? 'block' : 'none'} " style="display: none;" >
            <div class="header" data-bind="text: resp"></div>
          </div>
          <div class="ui error message" data-bind="style: { display: error() ? 'block' : 'none'} " style="display: none;" >
            <div class="header" data-bind="text: error"></div>
          </div>
          <p>Please enter the email your account is registered under.</p>
          <div class="field">
            <label>Email</label>
            <div class="ui left labeled icon input">
              <input type="text" data-bind="value: email">
              <i class="mail outline icon"></i>
              <div class="ui corner label">
                <i class="icon asterisk"></i>
              </div>
            </div>
          </div>
		  <div class="ui blue submit button" data-bind="click: PasswordResetRequest">Submit</div>
        </form>
      </div>
    </div>
  </div><!-- /end column -->
</div><!-- /end passwordResetRequest -->