<div id="signup" class="ui error form segment" style="display: none;" data-bind="visible: show, css: { loading: addingUser}">
  <div class="ui error message" style="display: none" data-bind="visible: errorMessage">
    <div class="header">Error</div>
    <p data-bind="html: errorMessage"></p>
  </div>
  <div class="two fields">
    <div class="field">
      <label>First Name</label>
      <input placeholder="First Name" type="text">
    </div>
    <div class="field">
      <label>Last Name</label>
      <input placeholder="Last Name" type="text">
    </div>
  </div>
  <div class="field">
    <label>Email</label>
    <input placeholder="email" type="text" data-bind="value: email">
  </div>
  <div class="field">
    <label>Password</label>
    <input type="password" data-bind="value: password">
  </div>
  <div class="inline field">
    <div class="ui checkbox">
      <input type="checkbox" id="terms">
      <label for="terms"></label>
    </div>
    <label>I agree to the terms and conditions</label>
  </div>
  <div class="ui blue submit button" data-bind="click: signup">Submit</div>
</div>